#!/bin/sh
#!/usr/bin/env bash

set -o posix

# awk -f test.awk -v packages_file="/home/user/base/unix/user/user_configuration.csv" -v commands_file="/home/user/base/list/source_commands.csv" -v config_file="/home/user/base/unix/user/user_configuration.csv"
time awk -f test.awk
