#!/bin/sh

if [ -f ./configuration-manager ] && [ -f ./src/init_system ]; then
    configuration_directory=./configuration
    data_directory=./data
    src_dir=src
else
    # xdg_config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
    # configuration_directory="$xdg_config_home"/configuration-manager
    path=$(cd -- "$(dirname "$0")" && pwd)
    configuration_directory="$path"/configuration
    data_directory="$path"/data
    src_dir="$path"/src
fi

. "$src_dir"/main
