#!/bin/sh

set -Eeuo posix pipefail

if [ -f ./configuration-manager ] && [ -f ./src/init_system ]; then
    configuration_directory=./config
    src_dir=src
else
    xdg_config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
    configuration_directory="$xdg_config_home"/configuration-manager
    path=$(cd -- "$(dirname "$0")" && pwd)
    src_dir="$path"/src
fi

source "$src_dir"/main
