#!/bin/sh

# link configuration manager to .local/bin
# set the path to the active configuration
SCRIPT_DIR="$(cd -- "$(dirname "$0")" && pwd)"
active_directory="$SCRIPT_DIR"/profile/active
find "${active_directory}" -type f -executable -print0 | xargs -0 ln -s -t ~/.local/bin/
