#!/bin/sh

# for now only this version is working
# do not forget to: pacman -R paru paru-debug before installing a new version with the script
git clone https://aur.archlinux.org/paru-git.git $HOME/.tools/paru
# git clone https://aur.archlinux.org/paru.git $HOME/.tools/paru
cd $HOME/.tools/paru
makepkg -si
rustup default stable
cd -
