#!/bin/sh

# Latest releases
URL="\
https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz\
"

# Nightly build
# URL="\
# https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz\
# "

cd $HOME && {
    rm -rf $HOME/.tools/nvim-linux64;
    curl -L ${URL} > neovim_tmp.tar.gz;
    tar -xf neovim_tmp.tar.gz;
    rm -rf neovim_tmp.tar.gz;
    mv nvim-linux64 $HOME/.tools/nvim-linux64;
    cd -;
}
