#!/bin/sh

ensure_directory_exist() {
    mkdir -p "$1"
}

request_confirmation() {
    question="$1"

    while true; do
        printf "\n%s [Y/n] " "$question"

        read -r answer

        case "$answer" in
            [YyOo]* )
                return 0
                ;;
            [Nn]* )
                return 1
                ;;
            * )
                echo "Please answer yes or no."
                ;;
        esac
    done
}
