#!/bin/sh

ensure_directory_exist() {
    mkdir -p "$1"
}

request_confirmation() {
    question="$1"

    while true; do
        printf "\n%s [Y/n] " "$question"

        read -r answer

        case "$answer" in
            [YyOo]* )
                return 0
                ;;
            [Nn]* )
                return 1
                ;;
            * )
                echo "Please answer yes or no."
                ;;
        esac
    done
}

backup() {
    backup_dir_hash=$(find "$active_directory" -type f -exec md5sum {} \; | md5sum | cut -d ' ' -f1)
    backup_location="$configuration_directory"/backup
    backup_dir="$backup_location/$backup_dir_hash"

    ensure_directory_exist "$backup_dir"

    mv "$active_directory"/* "$backup_dir"

    echo " Backup created: $backup_dir"
}

activate() {
    profile_name="${profile_name:-unknown}"

    printf ':: Activating [%s]...\n' "$profile_name"

    active_directory="$configuration_directory"/active
    ensure_directory_exist "$active_directory"

    output_directory="$1"

    if [ -z "$(find "$active_directory" -maxdepth 1 -type f 2>/dev/null)" ]; then
        echo "No files to back up in: $active_directory"
    else
        backup
    fi

    cp -r "$output_directory"/* "$active_directory"

    printf ' [%s] activated\n' "$profile_name"
}
